apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  selector:
    app: ollama
  ports:
  - port: {{ .Values.ollama.port }}
    targetPort: {{ .Values.ollama.port }}
    name: api
  type: {{ .Values.ollama.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: {{ .Values.ui.port }}
    name: http
    {{- if eq .Values.ui.service.type "NodePort" }}
    nodePort: {{ .Values.ui.service.nodePort }}
    {{- end }}
  type: {{ .Values.ui.service.type }}
