apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmr-pvc
  labels:
    {{- include "local-llm.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
